### ISSUE TITLE
Feature Request: tap_action to navigate to another view.

### ISSUE THREAD

**Issue by jimz011** [kalkih/simple-weather-card#18]
Hi, I will request a feature this way. Is there any possibility to add a tap_action (or hold_action) like other cards do? When I press on the weather now it will open up the more-info view. Yes I know I can use popup cards but I wish tapping on the weather can navigate me to the weather view.

I hope this is possible, and if you can’t add it, is there a way for me to do it myself? If yes will it require me to learn a lot of js?

**Comment by kalkih** [comment]
Hey,
I wish there was a custom card with this functionality, which you then could wrap other cards in.

It should be fairly simple, but would be more complex depending on the amount of "actions" available for the "tap_action", if you get what I mean.
Navigating to another view should be fairly easy since we could just do a redirect, I think.

**Comment by jimz011** [comment]
Well navigation is the only thing I can really use. But I guess having it do a service-call would help others making this beautiful weather card more functional.

**Comment by kalkih** [comment]
Okay, let's add the nav action initially and we could always add more actions later I guess 🙂

**Comment by kalkih** [comment]
Should now be possible in the latest release!
```yaml
- type: custom:simple-weather-card
  entity: weather.smhi_home
  tap_action:
    action: navigate
    navigation_path: /lovelace/3/
```
